Tuning cycle explanations
ROCmSoftwarePlatform/MITunaX pull request #746
Opened 2022-07-29 19:37 UTC by cderb

2022-07-29 20:05 UTC, alexandraBara requested changes

2022-07-29 20:05 UTC, alexandraBara commented on doc/TuningCycle.md
> +fin steps include miopen_perf_compile, miopen_perf_eval, miopen_find_compile, miopen_find_eval
```suggestion
Fin steps include: miopen_perf_compile, miopen_perf_eval, miopen_find_compile and miopen_find_eval.
```

2022-07-29 20:05 UTC, alexandraBara commented on doc/TuningCycle.md
> +./go_fish.py --local_machine --update_applicability --session_id 1
Add every command in quotations so it shows up nicely formatted and distinct from text.

```suggestion
```./go_fish.py --local_machine --update_applicability --session_id 1```
```

2022-07-29 20:05 UTC, alexandraBara commented on doc/TuningCycle.md
> +Finally time to start executing the jobs. To compile the jobs supply the session id
```suggestion
Once prerequisites are set, tuning can begin. To compile the jobs supply the session id
```

2022-07-29 20:05 UTC, alexandraBara commented on doc/TuningCycle.md
> +The job is ready for evaluation after the compile step, this command is similar to the previous
```suggestion
Once compile jobs have been started, the evaluation step can begin. This command is similar to the previous
```

2022-07-29 20:05 UTC, alexandraBara commented on doc/TuningCycle.md
> +To export the results the export_db.py script can be run with options
Add some more details that these results are exported into a .db or .fdb txt format and contains the information from the central tuning DB.

2022-07-29 21:01 UTC, cderb commented on doc/TuningCycle.md
> +## Tuning Steps
This should do quite well.

2022-08-01 13:53 UTC, alexandraBara approved these changes

2022-08-02 14:18 UTC, alexandraBara approved these changes
LGTM

2022-08-03 17:50 UTC, JehandadKhan approved these changes

2022-08-03 17:50 UTC, merged