Tuna- merge_db : unused variables are removed
ROCmSoftwarePlatform/MITunaX pull request #792
Opened 2022-10-14 14:37 UTC by technicalgrp89

Tuna - merge_db.py
Some of the unused variables are removed.

2022-11-23 22:07 UTC, cderb requested changes

2022-11-23 22:07 UTC, cderb commented on tests/test_utility.py
> +  test_get_mmi_env_vars
unnecessary, pytest will call all functions in the file beginning with test_

2022-11-23 22:07 UTC, cderb commented on tests/test_utility.py
> +  assert (retvalue == False)
The outcome of this test depends on the machine it is ran on. This test won't be consistent across machines.

2022-11-23 22:07 UTC, cderb commented on tests/test_utility.py
> +  assert 'testdb' == (env_vars['db_name'])
Where are the strings here inserted into the environment?
It doesn't look like this test does it.
Tests should be self contained.

2022-11-23 22:07 UTC, cderb commented on tests/test_utility.py
> +  assert (retvalue == False)
and here

2022-11-23 22:07 UTC, cderb commented on tests/test_utility.py
> +  assert 'xyz' == env_vars['gateway_user']
and here

2022-12-05 23:07 UTC, technicalgrp89 commented
Loooks like duplicate entry. All are addressed in previous PR and merged.

2022-12-05 23:24 UTC, closed without merging

2022-12-05 23:24 UTC, technicalgrp89 commented
duplicate entry. All are addressed in previous PR and merged https://github.com/ROCmSoftwarePlatform/MITuna/pull/791