Batchnorm.py - Type Annotations Support
ROCmSoftwarePlatform/MITunaX pull request #863
Opened 2023-03-08 20:36 UTC by technicalgrp89

tuna/miopen/driver/batchnorm.py
-- type hints
-- mypy compatibility
-- utility.groovy to execute the mypy cmd

2023-03-10 16:58 UTC, cderb requested changes

2023-03-10 16:58 UTC, cderb commented on tuna/miopen/driver/batchnorm.py
>      return BNConfig(**self.compose_tensors(keep_id))
BNConfig is not a dict

2023-03-10 16:58 UTC, cderb commented on tuna/miopen/driver/batchnorm.py
>      return arg_valid(tok1, tok2)
arg_valid returns a bool

2023-03-10 16:58 UTC, cderb commented on tuna/miopen/driver/batchnorm.py
>      return self.parse_bn_row(db_obj)
Remove return.

2023-03-13 14:23 UTC, cderb requested changes

2023-03-13 14:23 UTC, cderb commented on tuna/miopen/driver/batchnorm.py
> +    self.direction: Union[str, int, None] = None
This won't be optional, they will also be a singular type. Consult the defaults.

2023-03-13 14:23 UTC, cderb commented on tuna/miopen/driver/batchnorm.py
> +  def get_check_valid(tok1: str, tok2: str) -> Callable[[str, str], bool]:
This does not return a callable.

2023-03-15 16:12 UTC, cderb requested changes

2023-03-15 16:12 UTC, cderb commented on tuna/miopen/driver/batchnorm.py
> +    self.direction: Union[str, int] = 'F'
only string

2023-03-15 16:12 UTC, cderb commented on tuna/miopen/driver/batchnorm.py
>      self.direction = int(self.forw) + 4 * int(self.back)
Change this self.direction (int) to a function local variable to avoid affecting the typing of self.direction.

2023-03-21 20:31 UTC, cderb approved these changes

2023-03-22 14:22 UTC, alexandraBara approved these changes

2023-03-22 20:30 UTC, merged