flask.py -  typehint support
ROCmSoftwarePlatform/MITunaX pull request #865
Opened 2023-03-10 17:55 UTC by technicalgrp89

2023-03-13 17:23 UTC, alexandraBara approved these changes

2023-03-21 20:35 UTC, cderb requested changes

2023-03-21 20:35 UTC, cderb commented on tuna/flask_example.py
> +    query: str = session.query(ConvolutionFindDB.valid,
Not a str. Will have to consult sqlalchemy docs for actual typing, but acts like a list.

2023-03-22 20:15 UTC, alexandraBara commented on tuna/flask_example.py
> +    query: str = session.query(ConvolutionFindDB.valid,
@technicalgrp89  i believe its a list of DB rows. You can check the API of SQLAlchemy here: https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Result.all if you search for '.all()' on this page you might find more details

2023-03-27 22:37 UTC, technicalgrp89 commented on tuna/flask_example.py
> +    query: str = session.query(ConvolutionFindDB.valid,
changed to list

2023-03-27 23:33 UTC, cderb approved these changes

2023-03-29 20:07 UTC, merged