Reduce tensor lookup time.
ROCmSoftwarePlatform/MITunaX pull request #874
Opened 2023-03-30 17:25 UTC by cderb

cache tensor table to improve lookup time in driver
correct default layout values

2023-03-30 19:44 UTC, alexandraBara requested changes

2023-03-30 19:44 UTC, alexandraBara commented on tuna/utils/db_utility.py
> +def build_dict_val_key(obj, exclude=['id']):
these need to be unit tested

2023-04-04 16:59 UTC, JehandadKhan approved these changes

2023-04-04 19:36 UTC, alexandraBara approved these changes

2023-04-04 21:25 UTC, technicalgrp89 approved these changes

2023-04-05 08:23 UTC, merged