Solver keyed fdb export
ROCmSoftwarePlatform/MITunaX pull request #890
Opened 2023-04-26 15:54 UTC by cderb

Export fdb with the top 4 solvers.

2023-04-26 19:54 UTC, alexandraBara requested changes

2023-04-26 19:54 UTC, alexandraBara commented on tuna/miopen/subcmd/export_db.py
> -  miopen_fdb = build_miopen_fdb(fdb_alg_lists)
If this is not called anywhere anymore, please remove

2023-04-26 19:54 UTC, alexandraBara commented on tuna/miopen/subcmd/export_db.py
> +def build_miopen_fdb_2(query):
this will need a utest, how does this pass the codecov?

2023-05-12 18:46 UTC, cderb commented on tuna/miopen/subcmd/export_db.py
> +def build_miopen_fdb_2(query):
There was no previous unit test, so the change did not register.

2023-05-12 20:47 UTC, cderb commented
If #894 is merged first I will handle the resolution here.

2023-05-15 14:21 UTC, alexandraBara approved these changes
I see where you and @reidkwja  are stepping on each others toes. @reidkwja  please integrate this branch/utest in your export_db branch. Make sure to keep your own yaml testing however.

2023-05-15 15:38 UTC, reidkwja commented on tests/test_export_db.py
> +def test_export_db():
I believe we can merge both testing files into one without removing much code...My tests are more focused on individual functional runs and callability while your test_export_db is more integrative and focused on ensuring that all functions run correctly relative to each others with the correct data parsing.

2023-05-15 18:15 UTC, reidkwja approved these changes

2023-05-15 19:01 UTC, merged