Tuna/parse_args.py - type hint support
ROCmSoftwarePlatform/MITunaX pull request #891
Opened 2023-04-26 16:31 UTC by technicalgrp89

mypy cmd support - utils.groovy

2023-04-27 16:55 UTC, alexandraBara requested changes

2023-04-27 16:55 UTC, alexandraBara commented on tuna/parse_args.py
> +  libs: List[Any] = [elem.value for elem in Library]
i dont think it should be any, it should be List[Library] or something like that

2023-05-02 16:39 UTC, alexandraBara approved these changes

2023-05-02 23:44 UTC, JehandadKhan commented
@reidkwja  Please help review this PR

2023-05-03 22:16 UTC, reidkwja approved these changes

2023-05-04 15:11 UTC, merged