Sp/db base/base_class.py - typehint support
ROCmSoftwarePlatform/MITunaX pull request #907
Opened 2023-06-01 19:57 UTC by technicalgrp89

2023-06-02 22:34 UTC, cderb requested changes

2023-06-02 22:34 UTC, cderb commented on tuna/dbBase/base_class.py
> +  update_ts: Column = Column(
If mypy doesn't complain about this I think it's better to leave the line as is, because the type is clearly shown by the constructor.

2023-06-02 22:34 UTC, cderb commented on tuna/dbBase/base_class.py
> +  valid: str = Column(TINYINT(1), nullable=False, server_default="1")
This is a Column.

2023-06-02 22:34 UTC, cderb commented on tuna/dbBase/base_class.py
> +BASE: DeclarativeMeta = declarative_base(cls=BASE)  #type: ignore
Why the type ignore?

2023-06-05 19:00 UTC, cderb commented on tuna/dbBase/base_class.py
> +BASE: DeclarativeMeta = declarative_base(cls=BASE)  #type: ignore
Appears to be a necessary fix against mypy.

2023-06-06 16:13 UTC, cderb commented on tuna/dbBase/base_class.py
> +  valid: Column = Column(TINYINT(1), nullable=False, server_default="1")
Please match type schema with previous fields. My preference is removing the typing, because it is visible by the constructor.

2023-06-08 11:20 UTC, msaudulhassan requested changes

2023-06-08 11:20 UTC, msaudulhassan commented on tuna/dbBase/base_class.py
> +  __table_args__: Dict[str, str] = {'mysql_engine': 'InnoDB'}
`Dict[str, All]` would be more general, covering non-string type arguments as well

2023-06-08 11:20 UTC, msaudulhassan commented on tuna/dbBase/base_class.py
> +  __mapper_args__: Dict[str, bool] = {'always_refresh': True}
same

2023-06-08 11:20 UTC, msaudulhassan commented on tuna/dbBase/base_class.py
>    id = Column(Integer, primary_key=True)
missing typehints

2023-06-08 20:20 UTC, msaudulhassan approved these changes

2023-06-12 17:04 UTC, cderb approved these changes

2023-06-12 22:16 UTC, merged