Driver layout fix
ROCmSoftwarePlatform/MITunaX pull request #937
Opened 2023-11-08 16:23 UTC by alexandraBara

Fixes tensor layouts for convolution when not all 3 layouts are specified through the MIOpenDriver. Behavior is now this: 

- explicit check that all 3 convolution tensor layouts match at the end of the constructor. If different layouts will be supported in the future, this will need to be updated.
- when not all 3 layout are specified, the specified layout will overwrite the default hardcoded layout (NCHW).
- when no layout is specified, the default NCHW populates all 3 tensor layouts (this is already existing behavior).

Appends all 3 layouts when composing a Driver obj from a db_row. Previously in_layout/fil_layout where omitted.
When constructing a driver obj from an fdb_key we now check that all 3 layouts match.

To display the final driver cmd post constructor call do:
```
print(driver)
```

2023-11-08 18:10 UTC, msaudulhassan requested changes

2023-11-08 18:10 UTC, msaudulhassan commented on tests/test_driver.py
> +  assert (d4_str["fil_layout" == "NHWC"])
Is this right?

2023-11-08 18:10 UTC, msaudulhassan commented on tuna/miopen/driver/base.py
> +
I'm not sure if layout_dict is serving any purpose. Is this correct?
```python
for layout in layouts:
  if layout in line:
    value_set.add(getattr(self, layout))

if len(value_set) != 1:
  raise ValueError(...)

for layout in layouts:
  setattr(self, layout, value_set[0])
```

2023-11-08 18:10 UTC, msaudulhassan commented on tests/test_driver.py
> +  assert driver4 == driver5
Would it help to also do layout checks on driver5?

2023-11-08 18:17 UTC, msaudulhassan commented on tests/test_driver.py
> +  assert (d4_str["fil_layout" == "NHWC"])
These asserts will always pass. I think what you want to do would require some string parsing

2023-11-08 18:25 UTC, alexandraBara commented on tests/test_driver.py
> +  assert (d4_str["fil_layout" == "NHWC"])
i just realized my brackets are off, ill update

2023-11-10 21:55 UTC, cderb approved these changes
LGTM
double checking: This ensures that in parsing of the MIOpenDriver command will populate all three layouts correctly.
Parsing for fdb-keys currently has correct behavior for layout parsing?

2023-11-13 17:50 UTC, alexandraBara commented
> LGTM double checking: This ensures that in parsing of the MIOpenDriver command will populate all three layouts correctly. Parsing for fdb-keys currently has correct behavior for layout parsing?

Both creating the ConvolutionDriver obj from fdb or Driver cmd would not populate all 3 layouts. However this behavior was only recently introduce since adding NHWC configs. I checked our DB and the only entries where tensor layouts and out_layout does not match is where one or more of those is a 3D layout, but all these entries have valid=0.

2023-11-17 07:54 UTC, msaudulhassan approved these changes
lgtm

2023-11-17 17:06 UTC, merged