Remove arch_full column from Machine and gather the same data in SessionRocMLIR where it's used
ROCmSoftwarePlatform/MITunaX pull request #940
Opened 2023-11-11 20:56 UTC by pcf000

Since machine.gpus retains all the data that was parsed to set arch_full, it turned out to be easy to remove the arch_full field and do the same work in add_new_session.

2023-11-13 17:55 UTC, cderb commented on tuna/machine.py
> -  arch_full: str = Column(Text, nullable=False, default=arch)
We can limit this to a one line change by changing this line to
```py
arch_full: str = ""
```

2023-11-16 16:40 UTC, cderb approved these changes

2023-11-16 16:56 UTC, cderb requested changes
arch_full should be removed from addMachine in var/utils.groovy.

2023-11-16 20:40 UTC, cderb approved these changes

2023-11-17 16:48 UTC, alexandraBara approved these changes

2023-11-17 17:02 UTC, merged