Enable conditional steps retrievals for evaluators
ROCmSoftwarePlatform/MITunaX pull request #941
Opened 2023-11-15 16:23 UTC by reidkwja

new -> compiled -> bar_lock

2023-11-16 21:15 UTC, cderb requested changes

2023-11-16 21:15 UTC, cderb commented on tuna/miopen/worker/fin_eval.py
>        return False
This should be evaluated after we've finished checking for all job times. After checking "compiled" and "new". Only when there are no more jobs.

2023-11-17 16:47 UTC, alexandraBara commented
What is the reason for implementing this? the job queue is going away completely once celery is fully implemented but I need to know what the use case is here, in case this is something i need to consider. Keep in mind that the entire job queue is being moved to celery -  which handles the implementation details for us.

2023-11-17 17:07 UTC, cderb commented
We need the evaluation process to be able to retrieve jobs from the new state as well. We are also trying to prioritize compiled jobs.

2023-11-17 17:12 UTC, cderb approved these changes

2023-11-17 17:12 UTC, cderb commented on tuna/miopen/worker/fin_eval.py
> +    return True
Safe to remove this function.

2023-11-20 17:18 UTC, alexandraBara approved these changes

2023-11-21 05:46 UTC, msaudulhassan approved these changes
LGTM. Here's a minor suggestion though

2023-11-21 05:46 UTC, msaudulhassan commented on tuna/miopen/worker/fin_eval.py
> +    return True
This can be replaced with
```python
super().get_job(find_state, set_state, imply_end)
```

2023-11-22 19:09 UTC, merged