Batched Load Jobs
ROCmSoftwarePlatform/MITunaX pull request #946
Opened 2023-11-30 15:32 UTC by msaudulhassan

load_jobs first tries to do a bulk insert into the database with all the jobs. This can fail in two cases: (1) there are too too many jobs, (2) some of the jobs to be inserted already exist in the database. If bulk insert fails, load_job reverts to inserting one job at a time, which is slow.

Proposed change:

If bulk commit fails, revert to "batched commits," wherein batches of jobs (say 1000 jobs at a time) are insert into the database. By using the `IGNORE` keyword, duplicates can be handled.

2023-11-30 16:19 UTC, cderb approved these changes
Remove debug lines, otherwise LGTM.

2023-11-30 16:19 UTC, cderb commented on tuna/miopen/subcmd/load_job.py
> +import pdb
cleanup

2023-11-30 16:19 UTC, cderb commented on tuna/miopen/subcmd/load_job.py
> +      print('\n')
cleanup

2023-12-01 16:43 UTC, alexandraBara requested changes
Please add this file to pylint, if it were linted it would complain that pdb import is not used, code looks good

2024-04-03 15:03 UTC, alexandraBara commented
Stale

2024-04-03 15:03 UTC, closed without merging