pylint test/checks support - tuna/utils folder
ROCmSoftwarePlatform/MITunaX pull request #951
Opened 2024-01-12 19:04 UTC by technicalgrp89

tuna/utils folder is enabled for the pylint checks.
cmd is added in utils groovy file to support the same

2024-01-12 20:32 UTC, alexandraBara requested changes

2024-01-12 20:32 UTC, alexandraBara commented on tuna/utils/db_utility.py
> +  #pylint: disable=dangerous-default-value
please add inline with the function declaration

2024-01-12 20:32 UTC, alexandraBara commented on tuna/utils/db_utility.py
>  def build_dict_val_key(obj: SimpleDict, exclude: List[str] = ['id']):
```suggestion
def build_dict_val_key(obj: SimpleDict, exclude: List[str] = ['id']):  #pylint: disable=dangerous-default-value
```

2024-01-12 23:26 UTC, cderb requested changes

2024-01-12 23:26 UTC, cderb commented on tuna/utils/db_utility.py
> +  #attr_list = [attr for attr in attribs]
You can remove this comment.

2024-01-17 23:52 UTC, alexandraBara approved these changes

2024-01-20 00:44 UTC, cderb approved these changes

2024-01-20 00:45 UTC, merged