Integrating logs storage for Tuna through Logstash and Elastic Search
ROCmSoftwarePlatform/MITunaX pull request #973
Opened 2024-07-19 19:09 UTC by reidkwja

This PR will integrate allow the Tuna codebase to integrate with logstash and elastic search infrastructure for logs storage and analysis.

2024-07-22 13:50 UTC, alexandraBara requested changes

2024-07-22 13:50 UTC, alexandraBara commented on tuna/utils/logger.py
> +
they dont need to be globals, you can write a getter function that returns the logstash handler and call it both inside setup_logger and set_usr_logger. Sample:
```
def get_logstash_logger():
  logstash_handler: AsynchronousLogstashHandler = AsynchronousLogstashHandler(
      host=logstash_host, port=logstash_port, database_path=logstash_path)
    logstash_formatter: LogstashFormatter = LogstashFormatter()
    logstash_handler.setFormatter(logstash_formatter)
  logstash_handler.setLevel(logging.INFO)
```
then move the os.getenvs inside the functions and something like:
```
if logstash_status:
  logger.addHandler(get_logstash__logger())
```

2024-07-23 14:19 UTC, alexandraBara approved these changes
looks good

2024-07-24 16:07 UTC, cderb requested changes

2024-07-24 16:07 UTC, cderb commented on tuna/utils/logger.py
> +    logstash_handler.setLevel(logging.INFO)
This could be made into a function. Which could return the handler + status.

2024-07-24 16:07 UTC, cderb commented on tuna/utils/logger.py
> +    logstash_handler.setLevel(logging.INFO)
Could re-use function here.

2024-07-25 14:08 UTC, alexandraBara commented on tuna/utils/logger.py
> +    logger.info("Logstash is disabled. Not sending logs to Logstash.")
we dont need this printout, only print when enabled is enough

2024-07-25 14:09 UTC, alexandraBara commented on tuna/utils/logger.py
> +    lgr.info("Logstash is disabled. Not sending logs to Logstash.")
same here

2024-07-26 17:40 UTC, cderb approved these changes

2024-07-29 16:13 UTC, merged