Add Broker envs
ROCmSoftwarePlatform/MITunaX pull request #978
Opened 2024-08-13 16:23 UTC by cderb

Adding broker envs to pipeline docker arg list.

2024-08-14 17:34 UTC, alexandraBara requested changes

2024-08-14 17:34 UTC, alexandraBara commented on docker-compose-flower.yaml
> +
this file was removed in my branch, i think yours adds it back. It was "replaced" with docker-compose-flower_rabbitmq.yaml

2024-08-14 17:35 UTC, alexandraBara commented on tuna/celery_app/README.md
> +Launch dockers through docker compose:
Also not sure why these changes show up here?

2024-08-19 14:36 UTC, alexandraBara approved these changes

2024-08-21 18:37 UTC, msaudulhassan approved these changes

2024-08-21 18:58 UTC, merged