update export_db script to export pdb in db.txt format
ROCmSoftwarePlatform/MITunaX pull request #986
Opened 2024-11-05 19:03 UTC by cderb

2024-11-08 19:35 UTC, alexandraBara requested changes

2024-11-08 19:35 UTC, alexandraBara commented on tuna/miopen/subcmd/export_db.py
> +def fin_net_cfg_job(cfg_lst):
should pass in config_type as well and can put in place "Not implemented " for non-conv case. It matters when u build the job and add the "direction" which is conv specific hardcoded. I would say throughout any new function you add here that has elements specific to conv, add the case for non-conv and throw ValueError() or something like that so we can leave a trace to update later.

2024-12-04 18:03 UTC, alexandraBara requested changes

2024-12-04 18:03 UTC, alexandraBara commented on tuna/miopen/subcmd/export_db.py
> +          "arch": 'gfx908',
should probably not be hardcoded here

2024-12-04 18:03 UTC, alexandraBara commented on tuna/miopen/subcmd/export_db.py
> +    logger.error(f"Config type not implemented: {config_type}")
nice!

2024-12-04 18:03 UTC, alexandraBara commented on tuna/miopen/subcmd/export_db.py
> +  """Analyze perf_dv entry"""
spell check

2024-12-04 18:03 UTC, alexandraBara commented on tuna/miopen/subcmd/export_db.py
> +def write_pdb(arch, num_cu, ocl, perf_db, filename=None):
probably not a good idea to default filename to None it seems like it needs to be not none based on your code

2024-12-06 16:14 UTC, reidkwja approved these changes

2025-01-07 15:42 UTC, cderb commented on tuna/miopen/subcmd/export_db.py
> +          "arch": 'gfx908',
Comment on line 109, fin expects a valid arch/cu in the fin command, but the network_config step will not use it.

2025-01-07 15:55 UTC, cderb commented on tuna/miopen/subcmd/export_db.py
> +def write_pdb(arch, num_cu, ocl, perf_db, filename=None):
get_filename would generate an appropriate name if filename is None.

2025-01-07 15:56 UTC, cderb commented on tuna/miopen/subcmd/export_db.py
> +  """Analyze perf_dv entry"""
fixed

2025-01-20 21:58 UTC, alexandraBara approved these changes

2025-01-20 22:05 UTC, merged